//##############################################################################
//###############     This file has been generated by EDROOM     ###############
//##############################################################################
 
#ifndef EDROOMDEPLOYMENT_H_
#define EDROOMDEPLOYMENT_H_
 
#include <edroom_glue/edroomdf.h>
#include <public/edroomsl_iface_v1.h>
 
 
//******************************************************************************
// include deployment edroom components
 
#include <public/ccsystemmng_iface_v1.h>
#include <public/ccledmng_iface_v1.h>
#include <public/ccdisplaysmng_iface_v1.h>
// ***********************************************************************
// class CEDROOMSystemMemory
// ***********************************************************************
 
class CEDROOMSystemMemory{
 
	//!Messages Memory of component comp2
	CEDROOMMessage	comp2Messages[10];
	bool	comp2MessagesMarks[10];
	CEDROOMQueue::CQueueNode	comp2QueueNodes[11];
	bool	comp2QueueNodesMarks[11];
 
	//!Messages Memory of component comp3
	CEDROOMMessage	comp3Messages[10];
	bool	comp3MessagesMarks[10];
	CEDROOMQueue::CQueueNode	comp3QueueNodes[13];
	bool	comp3QueueNodesMarks[13];
 
	//!Messages Memory of component comp4
	CEDROOMMessage	comp4Messages[10];
	bool	comp4MessagesMarks[10];
	CEDROOMQueue::CQueueNode	comp4QueueNodes[13];
	bool	comp4QueueNodesMarks[13];
 
	public:
 
	CCSystemMng::CEDROOMMemory comp2Memory;
	CCLEDMng::CEDROOMMemory comp3Memory;
	CCDisplaysMng::CEDROOMMemory comp4Memory;
 
//!Set Memory
	void SetMemory();
};
 
class CEDROOMSystemCommSAP{
 
	 friend class CEDROOMSystemDeployment;
//!Communication Service Access Point
 
	CEDROOMLocalCommSAP m_localCommSAP;
 
 
//!Conections
 
	CEDROOMLocalConnection connections[2];
 
	CCSystemMng   * mp_comp2;
	CCLEDMng   * mp_comp3;
	CCDisplaysMng   * mp_comp4;
 
 
//!Set Components
 
	void SetComponents(CCSystemMng   *p_comp2,
							CCLEDMng   *p_comp3,
							CCDisplaysMng   *p_comp4);
 
 
//Signal Conversion
 
	static TEDROOMSignal C2SystemMng_PDisplaysMngCtrl__C4DisplaysMng_PDisplaysMngCtrl(TEDROOMSignal signal);
	static TEDROOMSignal C4DisplaysMng_PDisplaysMngCtrl__C2SystemMng_PDisplaysMngCtrl(TEDROOMSignal signal);
 
//Signal Conversion
 
	static TEDROOMSignal C2SystemMng_PLEDMngCtrl__C3LEDMng_PLEDMngCtrl(TEDROOMSignal signal);
	static TEDROOMSignal C3LEDMng_PLEDMngCtrl__C2SystemMng_PLEDMngCtrl(TEDROOMSignal signal);
 
 
//!Register Interfaces
	void RegisterInterfaces();
 
//!Set Local Connections
	void SetLocalConnections();
 
//!Set Remote Connections
	void SetRemoteConnections();
 
//!Set Connections
	void SetConnections();
 
};
 
class CEDROOMSystemDeployment{
 
//!Kernel
	Pr_Kernel	kernel;
 
#ifdef CONFIG_EDROOMDEPLOYMENT_NEED_TASK
 
//!Main Task
static Pr_TaskRV_t main_task(Pr_TaskP_t);
 
#endif
	CEDROOMSystemMemory   systemMemory;
	CEDROOMSystemCommSAP  systemCommSAP;
 
	CCSystemMng   * mp_comp2;
	CCLEDMng   * mp_comp3;
	CCDisplaysMng   * mp_comp4;
 
	public:
 
	CEDROOMSystemDeployment();
 
//!Deployment Configuration
	void Config(CCSystemMng   *p_comp2,
					CCLEDMng   *p_comp3,
					CCDisplaysMng   *p_comp4);
 
//!Deployment Start
	void Start();
 
//!StartComponents
	void StartComponents();
//!Config Components
 
	CCSystemMng::CEDROOMMemory 		* GetComp2Memory(){return &systemMemory.comp2Memory;}
	CCLEDMng::CEDROOMMemory 		* GetComp3Memory(){return &systemMemory.comp3Memory;}
	CCDisplaysMng::CEDROOMMemory 		* GetComp4Memory(){return &systemMemory.comp4Memory;}
 
};
#endif
