//##############################################################################
//###############     This file has been generated by EDROOM     ###############
//##############################################################################
 
#include <public/edroom_glue.h>
 
 
//******************************************************************************
// include deployment edroom components
 
#include <public/ccsystemmng_iface_v1.h>
#include <public/ccledmng_iface_v1.h>
#include <public/ccdisplaysmng_iface_v1.h>
 
#ifdef CONFIG_EDROOMBP_DEPLOYMENT_NEED_TASK
 
	CEDROOMSystemDeployment systemDeployment;
 
#endif
 
 
 
rtems_task Init (uint32_t arg){
 
 
 
#ifndef CONFIG_EDROOMBP_DEPLOYMENT_NEED_TASK
 
	CEDROOMSystemDeployment systemDeployment;
 
#endif
 
 
	CCSystemMng	comp2(2, 11, EDROOMprioHigh, 1024, systemDeployment.GetComp2Memory());
	CCLEDMng	comp3(3, 13, EDROOMprioNormal, 1024, systemDeployment.GetComp3Memory());
	CCDisplaysMng	comp4(4, 13, EDROOMprioLow, 1024, systemDeployment.GetComp4Memory());
 
	systemDeployment.Config(&comp2, &comp3, &comp4);
 
	systemDeployment.Start();
 
	;
 
}
